[package]
name = "doc_anal"
version = "0.1.0"
edition = "2021"

[dependencies]
cfb = "0.10"
byteorder = "1.5"
toml = "0.8.12"
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "0.12.4"
struct_iterable = "0.1.1"
ts-rs = "9.0"